### ISSUE TITLE
Limitaion

### ISSUE THREAD

**Issue by splimter** [Fethi1/univ-project#10]
### Firebase Store Limitation
![image](https://user-images.githubusercontent.com/11891837/56079877-908ede00-5dfa-11e9-8f97-cab02765beb3.png)

### Notes

User can **Upload** 20000 files per day.
User can **Read** 50000 content per day.
User can **Download** 50000 files per day.

Storage will be used for **Pending** files, Approved files will be moved into other Cloud Storage Services.

### Firebase Server Lifetime
![image](https://user-images.githubusercontent.com/11891837/56081632-cab6aa80-5e0f-11e9-9fe2-19d1ae203f5f.png)

* Red -> Server Down.
* Yallow/Orange ->Slow Server.

**Comment by Fethi-Hamdani** [comment]
we can find a solution for that, emm how much do you estimate all the data size of each spec apart?

**Comment by splimter** [comment]
@Fethi1 
At Min 0.5 GB Max 1.5 GB per spec (per year) ex: IT 2nd year.
So for the entier Licence per spec
At min 1.5GB Max 4.5GB

If we only use the provided Firebase sotrage we will **Only** cover **ONE** Licence Spec (ex: only IT licene, master or other spec).

That why We Will use only the **Firebase sotrage** for Pending Files.

**Comment by splimter** [comment]
> @Fethi1
> At Min 0.5 GB Max 1.5 GB per spec (per year) ex: IT 2nd year.
> So for the entier Licence per spec
> At min 1.5GB Max 4.5GB
> 
> If we only use the provided Firebase sotrage we will **Only** cover **ONE** Licence Spec (ex: only IT licene, master or other spec).
> 
> That why We Will use only the **Firebase sotrage** for Pending Files.

Value detail based on **REAL** file size for entire year:
* IT 2nd year (1.2GO) 
* Frensh 1st year (290mo)
