### ISSUE TITLE
Download from Firebase

### ISSUE THREAD

**Issue by splimter** [Fethi1/univ-project#6]
Where to Store Data?

**Comment by Fethi-Hamdani** [comment]
store it on internal storage of the device and we store the path of each file in the local application storage so it won't be have a big size also files won't be lost if app crashed or accidently uninstalled

**Comment by Fethi-Hamdani** [comment]
and we can add a feature for example i started my IT app so the app go fetch for available predownloaded  IT files from our firebase and bring them and store their path too and users won't have to download them each time
